//! Parity tests: assert wiz4rd-math output equals `@pancakeswap/v3-sdk`
//! (TypeScript) output, vector by vector.
//!
//! The corpus lives in `test-vectors/vectors.json`, generated by
//! `test-vectors/generate.mjs` from the pinned `@pancakeswap/v3-sdk@3.10.1`.
//! Regenerate it only when the SDK pin changes:
//!
//! ```bash
//! cd test-vectors && npm install && npm run generate
//! ```
//!
//! Because PancakeSwap forked Uniswap V3's math unchanged, these vectors also
//! validate the math against the canonical on-chain implementation.

use alloy::primitives::{aliases::I24, aliases::U160, I256, U256};
use serde::Deserialize;

use crate::{
    add_delta, compute_swap_step, get_amount_0_delta, get_amount_1_delta, get_sqrt_ratio_at_tick,
    get_tick_at_sqrt_ratio, FullMath, SqrtPriceMath,
};

const VECTORS: &str = include_str!("../../../test-vectors/vectors.json");

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Vectors {
    tick_to_sqrt_price: Vec<TickToSqrtPrice>,
    sqrt_price_to_tick: Vec<SqrtPriceToTick>,
    mul_div_rounding_up: Vec<MulDivRoundingUp>,
    next_sqrt_price_from_input: Vec<NextSqrtPriceFromInput>,
    next_sqrt_price_from_output: Vec<NextSqrtPriceFromOutput>,
    amount0_delta: Vec<AmountDelta>,
    amount1_delta: Vec<AmountDelta>,
    add_delta: Vec<AddDelta>,
    swap_step: Vec<SwapStep>,
    position_amounts: Vec<PositionAmounts>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct TickToSqrtPrice {
    tick: i64,
    sqrt_price_x96: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct SqrtPriceToTick {
    sqrt_price_x96: String,
    tick: i64,
}

#[derive(Debug, Deserialize)]
struct MulDivRoundingUp {
    a: String,
    b: String,
    denominator: String,
    result: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct NextSqrtPriceFromInput {
    #[serde(rename = "sqrtPX96")]
    sqrt_px96: String,
    liquidity: String,
    amount_in: String,
    zero_for_one: bool,
    result: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct NextSqrtPriceFromOutput {
    #[serde(rename = "sqrtPX96")]
    sqrt_px96: String,
    liquidity: String,
    amount_out: String,
    zero_for_one: bool,
    result: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AmountDelta {
    sqrt_a: String,
    sqrt_b: String,
    liquidity: String,
    round_up: bool,
    result: String,
}

#[derive(Debug, Deserialize)]
struct AddDelta {
    x: String,
    y: String,
    result: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct SwapStep {
    sqrt_current: String,
    sqrt_target: String,
    liquidity: String,
    amount_remaining: String,
    fee_pips: u32,
    sqrt_ratio_next_x96: String,
    amount_in: String,
    amount_out: String,
    fee_amount: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct PositionAmounts {
    tick_current: i64,
    tick_lower: i64,
    tick_upper: i64,
    sqrt_ratio_x96: String,
    liquidity: String,
    amount0: String,
    amount1: String,
}

fn vectors() -> Vectors {
    serde_json::from_str(VECTORS).expect("test-vectors/vectors.json must be valid")
}

fn u256(s: &str) -> U256 {
    U256::from_str_radix(s, 10).expect("decimal U256")
}

fn u160(s: &str) -> U160 {
    U160::from_str_radix(s, 10).expect("decimal U160")
}

fn u128v(s: &str) -> u128 {
    s.parse().expect("decimal u128")
}

fn i256v(s: &str) -> I256 {
    let raw: i128 = s.parse().expect("decimal i128 (vectors fit)");
    I256::try_from(raw).expect("i128 fits I256")
}

fn i24(t: i64) -> I24 {
    I24::try_from(t as i32).expect("tick fits I24")
}

#[test]
fn parity_tick_to_sqrt_price() {
    for v in &vectors().tick_to_sqrt_price {
        let got = get_sqrt_ratio_at_tick(i24(v.tick)).unwrap();
        assert_eq!(got.to_string(), v.sqrt_price_x96, "tick {}", v.tick);
    }
}

#[test]
fn parity_sqrt_price_to_tick() {
    for v in &vectors().sqrt_price_to_tick {
        let got = get_tick_at_sqrt_ratio(u160(&v.sqrt_price_x96)).unwrap();
        assert_eq!(
            got.to_string(),
            v.tick.to_string(),
            "sqrt {}",
            v.sqrt_price_x96
        );
    }
}

#[test]
fn parity_mul_div_rounding_up() {
    for v in &vectors().mul_div_rounding_up {
        let got =
            FullMath::mul_div_rounding_up(u256(&v.a), u256(&v.b), u256(&v.denominator)).unwrap();
        assert_eq!(got.to_string(), v.result, "{v:?}");
    }
}

#[test]
fn parity_next_sqrt_price_from_input() {
    for v in &vectors().next_sqrt_price_from_input {
        let got = SqrtPriceMath::get_next_sqrt_price_from_input(
            u160(&v.sqrt_px96),
            u128v(&v.liquidity),
            u256(&v.amount_in),
            v.zero_for_one,
        )
        .unwrap();
        assert_eq!(got.to_string(), v.result, "{v:?}");
    }
}

#[test]
fn parity_next_sqrt_price_from_output() {
    for v in &vectors().next_sqrt_price_from_output {
        let got = SqrtPriceMath::get_next_sqrt_price_from_output(
            u160(&v.sqrt_px96),
            u128v(&v.liquidity),
            u256(&v.amount_out),
            v.zero_for_one,
        )
        .unwrap();
        assert_eq!(got.to_string(), v.result, "{v:?}");
    }
}

#[test]
fn parity_amount0_delta() {
    for v in &vectors().amount0_delta {
        let got = get_amount_0_delta(
            u160(&v.sqrt_a),
            u160(&v.sqrt_b),
            u128v(&v.liquidity),
            v.round_up,
        )
        .unwrap();
        assert_eq!(got.to_string(), v.result, "{v:?}");
    }
}

#[test]
fn parity_amount1_delta() {
    for v in &vectors().amount1_delta {
        let got = get_amount_1_delta(
            u160(&v.sqrt_a),
            u160(&v.sqrt_b),
            u128v(&v.liquidity),
            v.round_up,
        )
        .unwrap();
        assert_eq!(got.to_string(), v.result, "{v:?}");
    }
}

#[test]
fn parity_add_delta() {
    for v in &vectors().add_delta {
        let got = add_delta(u128v(&v.x), i256v(&v.y).try_into().unwrap()).unwrap();
        assert_eq!(got.to_string(), v.result, "{v:?}");
    }
}

#[test]
fn parity_swap_step() {
    for v in &vectors().swap_step {
        let (next, amount_in, amount_out, fee_amount) = compute_swap_step(
            u160(&v.sqrt_current),
            u160(&v.sqrt_target),
            u128v(&v.liquidity),
            i256v(&v.amount_remaining),
            v.fee_pips,
        )
        .unwrap();
        assert_eq!(next.to_string(), v.sqrt_ratio_next_x96, "next {v:?}");
        assert_eq!(amount_in.to_string(), v.amount_in, "amountIn {v:?}");
        assert_eq!(amount_out.to_string(), v.amount_out, "amountOut {v:?}");
        assert_eq!(fee_amount.to_string(), v.fee_amount, "feeAmount {v:?}");
    }
}

/// TS `PositionMath.getToken0Amount/getToken1Amount` use the same
/// round-down delta math; replicate the exact branch logic here.
#[test]
fn parity_position_amounts() {
    for v in &vectors().position_amounts {
        let sqrt = u160(&v.sqrt_ratio_x96);
        let liq = u128v(&v.liquidity);
        let lower = u160(
            &get_sqrt_ratio_at_tick(i24(v.tick_lower))
                .unwrap()
                .to_string(),
        );
        let upper = u160(
            &get_sqrt_ratio_at_tick(i24(v.tick_upper))
                .unwrap()
                .to_string(),
        );

        let amount0 = if v.tick_current < v.tick_lower {
            get_amount_0_delta(lower, upper, liq, false).unwrap()
        } else if v.tick_current < v.tick_upper {
            get_amount_0_delta(sqrt, upper, liq, false).unwrap()
        } else {
            U256::ZERO
        };
        let amount1 = if v.tick_current < v.tick_lower {
            U256::ZERO
        } else if v.tick_current < v.tick_upper {
            get_amount_1_delta(lower, sqrt, liq, false).unwrap()
        } else {
            get_amount_1_delta(lower, upper, liq, false).unwrap()
        };

        assert_eq!(amount0.to_string(), v.amount0, "amount0 {v:?}");
        assert_eq!(amount1.to_string(), v.amount1, "amount1 {v:?}");
    }
}
